# Generated by Django 3.0.2 on 2020-02-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
