# Generated by Django 3.0.2 on 2020-02-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_words_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='key',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
